### ISSUE TITLE
Trivial typo in Surgisphere post: 30 May 2020

### ISSUE THREAD

**Issue by JoeCursio** [ellisp/ellisp.github.io#48]
In the paragraph discussing LinkedIn profiles, you accidental wrote “CE” instead of “CEO.” I only brought this up because you later made fun of their typo.

**Comment by ellisp** [comment]
Thanks for pointing this out. As it happens this was not a typo, I was just a bit lax in sometimes saying CE for "Chief Executive" and sometimes CEO for "Chief Executive Officer". I find that the two terms are used synomymously. I should have been consistent, but it's not as bad as "Scoence" for "Science".

I won't edit it retrospectively just to make it consistent because I find that sometimes makes the article appear as new in people's RSS feeds which can cause confusion, so I only do it if it's important.
