### ISSUE TITLE
Possible data supporting wearing of masks

### ISSUE THREAD

**Issue by bgee-git** [ellisp/ellisp.github.io#50]
Is it worth doing an in-depth look at Victoria’s new cases of Covid-19 data between the dates of 9 July (Initial Melbourne lockdown), 22 July (mandatory mask wearing in Melbourne), and 3 August (introduction of Stage 4 restrictions).  All recommendations to introduce mandatory mask wearing has been based on advice, not proof, that they help control spread of the virus.  It appears there is a very short period of data that shows mask wearing is driving the current decrease in new cases.

**Comment by ellisp** [comment]
I think this is dealt with (to a degree) by a change I made in my modelling of time-varying R so that there can be a level shift down or up at named times, and I have fed it the times there were significant changes in lockdown etc. I think the data are too thin and too many confounding factors to draw strong conclusions on just masks from just Victoria data however. Difficult (but good) question.

There is some Imperial College modelling that's looked at this across countries using similar methods to what I have, but much more thoroughly and with more data.
